apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: g1-smart-glasses-claim
  namespace: toska-playground
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: data-2
  volumeMode: Filesystem
